.libPaths()
available.packages()
packageDescription("MASS")
install.packages("MASS","stats")
install.packages(c("MASS","stats")) 
library("MASS","stats")
View(Aids2)
detach(package : MASS)
View(Aids2)
remove.packages("MASS")
library(MASS)
install.packages("kernSmooth")
library(KernSmooth)
